### ISSUE TITLE
TA comment: 使用者需求以及需求規格書

### ISSUE THREAD

**Issue by jo-ym** [datsxhero/BaseProject-Cpp#1]
1. "需求規格書"文件中每個功能請“分項”至少寫出簡介（你們有寫）、input/output、限制（若有）、流程（至少要有簡單版，能拿來驗收的）（-30）

*若有修改，請在此issue下回覆，否則不予修改及加分。

**Comment by datsxhero** [comment]
已上傳修改

**Comment by jo-ym** [comment]
> 已上傳修改

OK 已修改ilearn上分數
